In [1]:
import numpy as np

In [2]:
arr_1d=np.array([1,2,3,4,5])
print(arr_1d)

arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [ ]:
#Elements wise multiplication
list_py=[1,2,3,4,5]
print(list_py*2)

array_np=np.array([1,2,3,4,5])
print(array_np*2)
#numpy has low operation cost

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [5]:
zeros=np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
once=np.ones((2,3))
print(once)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
const=np.full((2,3),5)
print(const)

[[5 5 5]
 [5 5 5]]


In [10]:
random=np.random.random((3,3))
print(random)

[[0.18041235 0.71130336 0.7152366 ]
 [0.31981021 0.74792683 0.11562694]
 [0.68012632 0.82623905 0.20941662]]


In [11]:
sequence=np.arange(0,10,2)
print(sequence)

[0 2 4 6 8]


In [12]:
vector=np.linspace(0,10,5)
print(vector)

[ 0.   2.5  5.   7.5 10. ]


In [13]:
matrix=np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [15]:
tensor=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(tensor)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [16]:
print(array_np.shape)
print(array_np.dtype)
print(array_np.size)
print(array_np.ndim)


(5,)
int64
5
1


In [21]:
array_y=np.arange(6)
array_y
reshape_y=array_y.reshape(2,3)
reshape_y
flatenned_y=array_y.flatten()
flatenned_y
ravelled_y=array_y.ravel()
ravelled_y
#raevl is only view not copy

array([0, 1, 2, 3, 4, 5])

In [22]:
transpose_y=array_y.T
print(transpose_y)

[0 1 2 3 4 5]
