In [2]:
import numpy as np
array=np.array([1,2,3,4,5,6,7,8,9,10])

In [5]:
array[1:11:2]
array[-1]

np.int64(10)

In [8]:
#2d array indexing and slicing 
array_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array_2d[:,2])    
print(array_2d[1,2])

[3 6 9]
6


In [9]:
#sorting
#sorting 1d
unsorted_array=np.array([10,9,8,7,6,5,4,3,2,1])
sorted_array=np.sort(unsorted_array)
print(sorted_array)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
#sorting 2d
unsorted_array_2d=np.array([[9,8,7],[6,5,4],[3,2,1]])
sorted_array_2d=np.sort(unsorted_array_2d)
print(sorted_array_2d)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [18]:
#sorting 2d
unsorted_array_2d = np.array([[9,8,7],[6,5,4],[3,2,1]])
sorted_array_2d = np.sort(unsorted_array_2d,axis=0)
print(sorted_array_2d)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [19]:
#Filtering the array 

array = np.array([1,2,3,4,5,6,7,8,9,10])
filtered_array = array[array % 2 == 0]
print(filtered_array)

[ 2  4  6  8 10]


In [20]:
# filter with mask
mask=array%2==0
filtered_array=array[mask]
print(filtered_array)

[ 2  4  6  8 10]


In [25]:
#where clause 

array = np.array([1,2,3,4,5,6,7,8,9,10])
filtered_array = np.where(array % 2 == 0)
array[filtered_array]

array([ 2,  4,  6,  8, 10])

In [29]:
condition=np.where(array%2==0)
condition1=np.where(array%2!=0,array+1,array-1)
print(condition1)

[ 2  1  4  3  6  5  8  7 10  9]


In [30]:
#adding and removing 
# merging

array_1=np.array([1,2,3,4,5])
array_2=np.array([6,7,8,9,10])
merged_array=np.concatenate((array_1,array_2))
print(merged_array)

[ 1  2  3  4  5  6  7  8  9 10]


In [32]:
#conpatibilty shapes 
a=np.array([1,2,3])
b=np.array([4,5])
print(a.shape==b.shape)

# adding new row to matrix

matrix=np.array([[1,2,3],[4,5,6]])
new_row=np.array([7,8,9])
matrix=np.vstack((matrix,new_row))
print(matrix)

False
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
# adding new column 

matrix = np.array([[1, 2, 3], [4, 5, 6]])
new_column = np.array([[7], [8]])  # Make sure new_column has 2 rows
matrix = np.hstack((matrix, new_column))
print(matrix)

[[1 2 3 7]
 [4 5 6 8]]


In [35]:
#deleteing 
matrix = np.array([[1, 2, 3], [4, 5, 6]])
deleted_row = np.delete(matrix, 0, axis=0)
deleted_column = np.delete(matrix, 1, axis=1)
print(deleted_row)
print(deleted_column)

[[4 5 6]]
[[1 3]
 [4 6]]
